# The CI for each commit, prints envs and content of GITHUB_EVENT_PATH
name: Debug

'on':
  push:
    branches:
      # 22.1 and 22.10
      - '2[1-9].[1-9][0-9]'
      - '2[1-9].[1-9]'
  pull_request_review:
  workflow_dispatch:
  workflow_call:

jobs:
  DebugInfo:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@a701ed95a46e6f2fb0df25e1a558c16356fae35a
